### ISSUE TITLE
we need Image preprocessing method

### ISSUE THREAD

**Issue by MokkeMeguru** [VLL-HD/FrEIA#28]
Hello, I try to find the method of transforming a discrete image to a continuous image.
So, I want to know how to implement like the preprocess method such as 
- https://github.com/fmu2/realNVP/blob/8d36691df215af3678440ccb7c01a13d2b441a4a/data_utils.py#L76-L121

- https://github.com/tensorflow/models/blob/master/research/real_nvp/real_nvp_multiscale_dataset.py#L1072-L1077

Thanks!

**Comment by ardizzone** [comment]
Hi, the easy way is to just copy the first function that you linked, and apply it to the input before you give it to the INN.
(And when sampling, apply the inverse).

Otherwise, if you want to have this in `FrEIA.modules`, either you can do it yourself, and we would be thrilled to receive a pull-request. Or you can raise it as a feature-request issue in https://github.com/VLL-HD/FrEIA-community , then we will try to assign some one to implement it.
