### ISSUE TITLE
Replicate ReversibleGraphNet Error

### ISSUE THREAD

**Issue by NikMolo** [VLL-HD/FrEIA#29]

**Comment by NikMolo** [comment]
Hello,
I am trying to replicate the tutorial part on Reversible Graph Net, however, I am getting the following error and I dont understand why.
![rev1](https://user-images.githubusercontent.com/50913519/78132311-ce767f00-741c-11ea-8c5c-0699f52f628a.JPG)
![rev](https://user-images.githubusercontent.com/50913519/78132324-d33b3300-741c-11ea-8a04-16b8e15a160d.JPG)
If you could give me any insight, I would be grateful!
Thank you in advance.

**Comment by Johnson-yue** [comment]
IndexError！！！  your network list has some problem！！

**Comment by NikMolo** [comment]
I realised that, however I used the exact same form of the code from the tutorial and I just added the module type inside the nodes. I don't see how I could have changed the indexing.

**Comment by ardizzone** [comment]
Hi!
I realize this is a late answer, sorry!

The problem is that you used `RNVPCouplingBlock`s for all the Nodes. For some of the nodes, you try to access not only `.out0`, but also `.out1`. But the `RNVPCouplingBlock` only has one output, so there is no `.out1`.
Instead, you could use e.g. the `Split1d` block to split into two streams (the kwargs are the same as for troch.split, specifically the `split_size_or_sections`).

We are working on a better tutorial this week and next, which will hopefully prevent the confusion in the future!
