### ISSUE TITLE
autoregressive flow?

### ISSUE THREAD

**Issue by jaekookang** [VLL-HD/FrEIA#44]
Thanks for the great work. 
I was wondering if FrEIA also provides an autoregressive-flow type of functionalities. I have multivariate time-series speech data which has input as audio features (12-d) and the output as framewise one-hot coded labels (9-d). Would it be possible to use FrEIA to model this type of data?

**Comment by ardizzone** [comment]
Hi!
Very interesting question!
It certainly can't be done out of the box, and will require implementing something yourself for now.
Of course, you could then easily wrap autoregressive operations as a module like the others in `FrEIA.modules`.

If you happen to do that, we would be thrilled about a pull request!
Otherwise, if you simply want to suggest the feature, feel free to open an issue in https://github.com/VLL-HD/FrEIA-community/
There, we collect larger feature request and so on, for us or the community to work on.
(We are still setting up the FrEIA-community repository this week, we will add more documents etc. throughout the next weeks)
