### ISSUE TITLE
Source Change Warning

### ISSUE THREAD

**Issue by salmanali88** [VLL-HD/FrEIA#46]
![Screenshot 2020-12-06 024236](https://user-images.githubusercontent.com/63067029/101260820-7c38eb00-376d-11eb-825c-b0fbb07aff1e.png)
Hello Everyone I am facing this issue anyone have the solution becuase it effect my results thanks in Advance

**Comment by ardizzone** [comment]
Hi! 
This is a pytorch issue as it seems, not specifically FrEIA.
Is your code public, then I could quickly check to see if it's anything obvious.

More specifically, it seems like `torch.nn.Module.dump_patches` is `True`, which is ok,
but the patchfiles that pytorch wants to save can't be saved somehow (perhaps a problem with using iPython).
Some suggestions:
- What happens if you run the script from the Anaconda terminal (should be included in your installation in windows). `cd` to the working directory, and then run `conda activate`, and then `python k-means-test.py`.
- Was the model trained on GPU and loaded to CPU, or vice versa?
- Did you update torch and FrEIA between training and loading again? Or using different conda environments for both?

Otherwise, maybe this issue can help:
https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/46
I will close this issue for now, as it is not pertaining to FrEIA directly, but feel free to let us know if there are further problems!

**Comment by salmanali88** [comment]
My code is working fine it was my mistake thanks for helping out

**Comment by ardizzone** [comment]
No problem, I'm glad it's working now! :wink:
