### ISSUE TITLE
Miss cbn_layer file

### ISSUE THREAD

**Issue by Johnson-yue** [VLL-HD/FrEIA#5]
Hi, when I will train cINN with LSUN dataset , I find the **from cbn_layer import *** has Error , because cbn_layer has not in your repo.

**Comment by ardizzone** [comment]
Thank you for pointing this out!

I just pushed 64a04cb, where the import is removed.
Nothing from that module was being used in the final model anyway, we just experimented with it historically.
I think it works now, otherwise feel free to re-open and I will be happy to help further.

I you are training LSUN Bedrooms, you could also try starting from the `colorization_minimal_example`, and expanding the model.
The code is a lot less convoluted, as it isn't the full research code.

**Comment by Johnson-yue** [comment]
ok, I will try minmal_example first , thank you , I think your idea is very good ,but I don't know how to debug this framework, so still learning
